# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caribbean Tech Forum
email_1: nissan@caribbeantechforum.com
email_2: joanna@caribbeantechforum.com
description: We're all about connecting Caribbean IT professionals and developers across industry spectrums and skill levels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://caribbeantechforum.github.io" # the base hostname & protocol for your site
twitter_username: carib_techforum
github_username:  caribbeantechforum
facebook_username: CaribbeanTechForum
# Build settings
markdown: kramdown
